<?xml version="1.0"?>
<robot name="fox" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="gazebo.urdf.xacro" />
  <xacro:include filename="lidar.urdf.xacro" />

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.31"/>
  <xacro:property name="base_length" value="0.31"/>
  <xacro:property name="base_height" value="0.31"/>
  
  <xacro:property name="ear_low_width" value="0.1"/>
  <xacro:property name="ear_low_length" value="0.02"/>
  <xacro:property name="ear_low_height" value="0.05"/>
  
  <xacro:property name="ear_high_width" value="0.06"/>
  <xacro:property name="ear_high_length" value="0.02"/>
  <xacro:property name="ear_high_height" value="0.04"/>
  
  <xacro:property name="eye_width" value="0.08"/>
  <xacro:property name="eye_length" value="0.005"/>
  <xacro:property name="eye_height" value="0.08"/>
  
  <xacro:property name="eye_reflect_width" value="0.04"/>
  <xacro:property name="eye_reflect_length" value="0.0025"/>
  <xacro:property name="eye_reflect_height" value="0.04"/>
  
  <xacro:property name="cheek_width" value="0.15"/>
  <xacro:property name="cheek_length" value="0.05"/>
  <xacro:property name="cheek_height" value="0.07"/>
  
  <xacro:property name="nose_long_width" value="0.05"/>
  <xacro:property name="nose_long_length" value="0.08"/>
  <xacro:property name="nose_long_height" value="0.05"/>
  
  <xacro:property name="nose_width" value="0.03"/>
  <xacro:property name="nose_length" value="0.01"/>
  <xacro:property name="nose_height" value="0.02"/>

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_ygap" value="0.02"/>
  <xacro:property name="wheel_zoff" value="0.08"/>
  <xacro:property name="wheel_xoff" value="0.12"/>

  <xacro:property name="caster_xoff" value="0.11"/>
  
  <material name="Orange">
    <color rgba="0.9921568627450981 0.13529411764705882 0.023529411764705882 1.0"/> 
  </material>
  
  <material name="White">
    <color rgba="1. 1. 1.0 1.0"/>
  </material>
  
  <material name="Black">
    <ambient> 0. 0. 0.0 0.0"</ambient>
    <color rgba="0. 0. 0.0 0.0"/>
  </material>
  

  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Orange"/>
    </visual>
    
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>
  
  <frame name="lidar_frame" attached_to='chassis'>
    <pose>0.8 0 0.5 0 0 0</pose>
  </frame>


  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>
  
  
  <!-- Ears -->
  <xacro:macro name="ear_low" params="prefix y_reflect">
    <link name="${prefix}_ear_low">
      <visual>
        <geometry>
          <box size="${ear_low_length} ${ear_low_width} ${ear_low_height}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      
      <collision>
        <geometry>
          <box size="${ear_low_length} ${ear_low_width} ${ear_low_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="0.1" w="${ear_low_width}" d="${ear_low_length}" h="${ear_low_height}"/>
    </link>

    <joint name="${prefix}_ear_low_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_ear_low"/>
      <origin xyz="0.0 ${y_reflect*0.1} ${-(wheel_radius+wheel_zoff-base_height-ear_low_height)}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  
  <xacro:ear_low prefix="right" y_reflect="1" />
  <xacro:ear_low prefix="left" y_reflect="-1" />
  
  
  <xacro:macro name="ear_high" params="prefix y_reflect">
    <link name="${prefix}_ear_high">
      <visual>
        <geometry>
          <box size="${ear_high_length} ${ear_high_width} ${ear_high_height}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      
      <collision>
        <geometry>
          <box size="${ear_high_length} ${ear_high_width} ${ear_high_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="0.1" w="${ear_high_width}" d="${ear_high_length}" h="${ear_high_height}"/>
    </link>

    <joint name="${prefix}_ear_high_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_ear_high"/>
      <origin xyz="0.0 ${y_reflect*(0.1+0.02)} ${-(wheel_radius+wheel_zoff-base_height-ear_high_height-ear_low_height)}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  
  <xacro:ear_high prefix="right" y_reflect="1" />
  <xacro:ear_high prefix="left" y_reflect="-1" />
  
  
  <!-- Eyes -->
  <xacro:macro name="eye" params="prefix y_reflect">
    <link name="${prefix}_eye">
      <visual>
        <geometry>
          <box size="${eye_length} ${eye_width} ${eye_height}"/>
        </geometry>
        <material name="Black"/>
      </visual>
      
      <collision>
        <geometry>
          <box size="${eye_length} ${eye_width} ${eye_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="0.01" w="${eye_width}" d="${eye_length}" h="${eye_height}"/>
    </link>

    <joint name="${prefix}_eye_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_eye"/>
      <origin xyz="${base_height/2} ${y_reflect*0.08} ${-(wheel_radius+wheel_zoff-base_height/2-0.1)}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  
  <xacro:eye prefix="right" y_reflect="1" />
  <xacro:eye prefix="left" y_reflect="-1" />
  
  <xacro:macro name="eye_reflect" params="prefix y_reflect">
    <link name="${prefix}_eye_reflect">
      <visual>
        <geometry>
          <box size="${eye_reflect_length} ${eye_reflect_width} ${eye_reflect_height}"/>
        </geometry>
        <material name="White"/>
      </visual>
      
      <collision>
        <geometry>
          <box size="${eye_reflect_length} ${eye_reflect_width} ${eye_reflect_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="0.01" w="${eye_reflect_width}" d="${eye_reflect_length}" h="${eye_reflect_height}"/>
    </link>

    <joint name="${prefix}_eye_reflect_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_eye_reflect"/>
      <origin xyz="${base_height/2+(eye_reflect_length+eye_length)/2} ${-(0.08+0.02)+(y_reflect*(0.08+0.02+0.06))} ${-(wheel_radius+wheel_zoff-base_height/2-0.12)}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  
  <xacro:eye_reflect prefix="right" y_reflect="1" />
  <xacro:eye_reflect prefix="left" y_reflect="0" />
  
  <!-- Cheek -->
  
  <link name="cheek_big">
    <visual>
      <geometry>
        <box size="${cheek_length} ${cheek_width} ${cheek_height}"/>
      </geometry>
      <material name="White"/>
    </visual>

    <collision>
      <geometry>
        <box size="${cheek_length} ${cheek_width} ${cheek_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="0.01" w="${cheek_width}" d="${cheek_length}" h="${cheek_height}"/>
  </link>

  <joint name="cheek_big_joint" type="fixed">
    <parent link="base_link"/>
    <child link="cheek_big"/>
    <origin xyz="${base_height/2+cheek_length/2} 0. ${-(wheel_radius+wheel_zoff-base_height/2-0.03)}" rpy="0 0 0"/>
  </joint>
  
  <!-- Nose -->
  
  <link name="nose_long">
    <visual>
      <geometry>
        <box size="${nose_long_length} ${nose_long_width} ${nose_long_height}"/>
      </geometry>
      <material name="White"/>
    </visual>

    <collision>
      <geometry>
        <box size="${nose_long_length} ${nose_long_width} ${nose_long_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="0.01" w="${nose_long_width}" d="${nose_long_length}" h="${nose_long_height}"/>
  </link>

  <joint name="nose_long_joint" type="fixed">
    <parent link="base_link"/>
    <child link="nose_long"/>
    <origin xyz="${base_height/2+cheek_length/2+nose_long_length/1.5} 0. ${-(wheel_radius+wheel_zoff-base_height/2-0.025)}" rpy="0 0 0"/>
  </joint>
  
  <link name="nose">
    <visual>
      <geometry>
        <box size="${nose_length} ${nose_width} ${nose_height}"/>
      </geometry>
      <material name="Black"/>
    </visual>

    <collision>
      <geometry>
        <box size="${nose_length} ${nose_width} ${nose_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="0.01" w="${nose_width}" d="${nose_length}" h="${nose_height}"/>
  </link>

  <joint name="nose_joint" type="fixed">
    <parent link="base_link"/>
    <child link="nose"/>
    <origin xyz="${base_height/2+cheek_length/2+nose_long_length+nose_length*2-0.002} 0. ${-(wheel_radius+wheel_zoff-base_height/2-0.025)}" rpy="0 0 0"/>
  </joint>
  
  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="White"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="left_wheel" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="right_wheel" x_reflect="-1" y_reflect="-1" />
  
  <xacro:property name="radius_caster" value="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
  
  <!-- Caster Wheel -->
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${radius_caster}"/>
      </geometry>
      <material name="Orange"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${radius_caster}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="0.1" r="${radius_caster}"/>
  </link>

  <joint name="caster_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
  </joint>
  
  
  <gazebo reference="front_caster">
      <material>Orange</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
  </gazebo>


</robot>
